title: capsh.net
url: https://capsh.net
author: Andrew Capshaw
description: Andrew Capshaw's personal blog. Mostly book reviews, sometimes other things. I always hope to write more and never do.
permalink: pretty
post_dirs: false
markdown: kramdown
future: true
paginate: 5
paginate_path: "/journal/:num/"
collections:
  lists:
    output: true
  work:
    output: true
sass:
  sass_dir: _sass
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-timeago
jekyll_timeago:
  depth: 1
feed:
  posts_limit: 20