title: Andrew Capshaw | personal site
url: https://capsh.net
author: Andrew Capshaw
description: A personal blog, rarely updated
highlighter: pygments
permalink: pretty
post_dirs: false
markdown: kramdown
future: true
collections:
  lists:
    output: true
  work:
    output: true
sass:
  sass_dir: _sass
plugins:
  - jekyll-feed